import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react';
import logo from '../images/inkwell-logo.png'
import Image from 'next/image';
import Button from '@/components/Button';
import FileInputButton from '@/components/FileInputButton';

const Home = () => {

  const [data, setData] = useState<string | null>(null);
  const [armUpload, setArmUpload] = useState<File | null>(null);
  const [tattooUpload, setTattooUpload] = useState<File | null>(null);

  const handleArmInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      setArmUpload(event.target.files[0]);
    }
  };

  const handleTattooInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      setTattooUpload(event.target.files[0]);
    }
  }

  const handleGenerate = () => {
    if (!armUpload || !tattooUpload) {
      return;
    }

    const formData = new FormData();
    formData.append('arm_file', armUpload);
    formData.append('tattoo_file', tattooUpload);

    fetch('http://localhost:5000/upload', {
      method: 'POST',
      body: formData,
    })
      .then(response => response.json())
      .then(data => {
        console.log(data)
        const img_src = `data:image/png;base64,${data.img}`;
        setData(img_src);
      })
      .catch(error => {
        console.error(error);
      });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo}>
          <Image src={logo.src} alt="inkwell logo" width='200' height='140' />
        </div>
        <div className={styles.wrapper}>
          {data && <img src={data} alt="random image" />}
          <Button onClick={handleGenerate} text='Generate' />
        </div>
        <div className={styles.buttonPanel}>
          <div>
            <FileInputButton onChange={handleArmInputChange} text='upload arm image'/>
          </div>
          <div>
            <FileInputButton onChange={handleTattooInputChange} text='upload tattoo'/>
          </div>
        </div>
        <div className={styles.buttonPanel}>
          <Button onClick={() => null} text='choose from existing models' />
          <Button onClick={() => null} text='choose from existing tattoos' />
        </div>
      </main>
    </>
  )
}

export default Home;
